# Generated by Django 5.1.1 on 2024-09-25 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_job_title', models.CharField(max_length=255)),
                ('goal_job_title', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('education_field', models.CharField(max_length=255)),
                ('graduation_year', models.DateField()),
                ('technical_skills', models.TextField()),
                ('soft_skills', models.TextField()),
                ('experience_job_title', models.CharField(max_length=255)),
                ('experience_duration', models.IntegerField()),
                ('year_of_resignation', models.DateField()),
                ('city1', models.CharField(max_length=100, null=True)),
                ('city2', models.CharField(max_length=100, null=True)),
                ('city3', models.CharField(max_length=100, null=True)),
                ('availability', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
