# Generated by Django 5.1.1 on 2024-09-26 05:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_careergoal_resume_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careergoal',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=api.models.CareerGoal.user_directory_path),
        ),
    ]
