# Generated by Django 5.1.4 on 2024-12-21 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_geminiresonse_feild_alter_geminiresonse_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='geminiresonse',
            old_name='feild',
            new_name='field',
        ),
        migrations.AddField(
            model_name='geminiresonse',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geminiresonse',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='geminiresonse',
            unique_together={('user', 'field')},
        ),
    ]
