# Generated by Django 5.1.4 on 2024-12-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_feild_geminiresonse_field_geminiresonse_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careergoal',
            name='goal_job_title',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
