# Generated by Django 5.1.4 on 2024-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_careergoal_goal_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careergoal',
            name='availability',
            field=models.CharField(blank=True, choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='city1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='city2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='city3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='current_job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='education',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='education_field',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='experience_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='experience_job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='goal_job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='graduation_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='soft_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='technical_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='year_of_resignation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
